[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py --break-system-packages",
  "python3 -m pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu --break-system-packages",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"